services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/s2925534/corroborly-site:main
    container_name: corroborly-site
    restart: unless-stopped
    ports:
      - "5110:3000"
